apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.iva.name }}
  labels:
    app: {{  .Values.iva.name  }}
spec:
  replicas: {{ .Values.iva.replicaCount }}
  selector:
    matchLabels:
      app: {{  .Values.iva.name  }}
  template:
    metadata:
      labels:
        app: {{  .Values.iva.name  }}
    spec:
    {{- with .Values.iva.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ .Values.iva.name }}
      securityContext:
        {{- toYaml .Values.iva.podSecurityContext | nindent 8 }}
      initContainers:
      - name: init
        securityContext:
          {{- toYaml .Values.iva.securityContext | nindent 12 }}
        image: {{ tpl .Values.iva.image.repository . | quote }}
        imagePullPolicy: {{ .Values.iva.image.pullPolicy }}
        command:
          - /bin/sh
        args:
          - -c
          - '( [ -f /opt/ivaconf/config.js ] && [ "{{ .Values.iva.configuration.overwrite }}" != "true" ] )
                && echo Configuration already exists
                || echo "Copy configuration. Overwrite = {{ .Values.iva.configuration.overwrite }}"
                     && cp -r /usr/local/apache2/htdocs/iva/conf/* /opt/ivaconf
                     && echo "opencga.host = \"{{ .Values.opencga.host }}\";" >> /opt/ivaconf/config.js
                     && echo "cellbase.hosts[0] = \"{{ .Values.cellbase.host }}\";" >> /opt/ivaconf/config.js'
        volumeMounts:
          - mountPath: /opt/ivaconf
            name: ivaconf
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.iva.securityContext | nindent 12 }}
        image: {{ tpl .Values.iva.image.repository . | quote }}
        imagePullPolicy: {{ .Values.iva.image.pullPolicy }}
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          {{- toYaml .Values.iva.resources | nindent 12 }}
        volumeMounts:
        - mountPath: /usr/local/apache2/htdocs/iva/conf
          name: ivaconf
      volumes:
      - azureFile:
          secretName: {{ .Values.azureStorageAccount.secretName }}
          shareName: {{ .Values.iva.volumes.ivaconf.shareName }}
        name: ivaconf
      {{- with .Values.iva.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.iva.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.iva.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
