{{- if and (.Values.azureStorageAccount.enabled) (.Values.azureStorageAccount.createSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.azureStorageAccount.secretName }}
  labels:
    {{- include "iva.labels" . | nindent 4 }}
type: "Opaque"
data:
  azurestorageaccountname: {{ .Values.azureStorageAccount.name | b64enc | quote }}
  azurestorageaccountkey: {{ .Values.azureStorageAccount.key | b64enc | quote }}
{{- end }}