{{- if .Values.master.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.master.name }}
  labels:
    {{- include "opencga.labels" . | nindent 4 }}
{{- end -}}
