apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencga.secretName" . }}
  labels:
    {{- include "opencga.labels" . | nindent 4 }}
type: "Opaque"
data:
  openCgaAdminPassword: {{ .Values.opencga.admin.password | b64enc | quote }}
  hdInsightSshPassword: {{ .Values.hadoop.sshPassword | b64enc | quote }}
  mongoDbPassword: {{ .Values.mongodb.password | b64enc | quote }}
