apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rest.name }}
  labels:
    {{- include "opencga.labels" . | nindent 4 }}
    app: {{  .Values.rest.name  }}
spec:
  type: {{ .Values.rest.service.type }}
  ports:
    - port: {{ .Values.rest.service.port }}
      targetPort: 9090
      protocol: TCP
      name: http
  selector:
    app: {{  .Values.rest.name  }}