execution:
  id: "k8s Jobs"
  queue: "queue1"
  azureCredentials: ""
  options:
    - "option1"
envs:
  - id: corpasome-grch37
    description: generate vcf for corpasome-grch37
    dataset:
      path: "/home/juanfe/training/dataset/"
      paired: true
    reference:
      path: "/home/juanfe/training/bwaindex37/Homo_sapiens.GRCh37.75.dna.chromosome.21.fa"
      index: "/home/juanfe/training/bwaindex37"
    aligner:
      skip: false
      name: "BWA 1.12"
      image: "opencb/opencga-ext-tools:2.3.0"
      command: "bwa mem ${PARAMS} ${INDEX}/Homo_sapiens.GRCh37.75.dna.chromosome.21.fa ${FASTQ1} ${FASTQ2} > ${OUTPUT}"
      params:
        - "-t 4"
    callers:
      - name: GATK v4.2.15
        skip: false
        image: "broadinstitute/gatk:4.2.15"
        command: "gatk.sh ${PARAMS}"
        params:
          - "INPUT=${BAM}"
          - "OUTPUT=${OUTPUT}"
  - id: corpasome-grch38
    description: generate vcf for corpasome-grch38
    dataset:
      path: "/home/juanfe/training/dataset/"
      paired: true
    reference:
      path: "/home/juanfe/training/bwaindex38/Homo_sapiens.GRCh37.75.dna.chromosome.21.fa"
      index: "/home/juanfe/training/bwaindex38"
    aligner:
      name: "BWA 1.12"
      image: "opencb/opencga-ext-tools:2.3.0"
      command: "bwa mem ${PARAMS} ${INDEX}/Homo_sapiens.GRCh37.75.dna.chromosome.21.fa ${FASTQ1} ${FASTQ2}> ${OUTPUT}"
      params:
        - "-t 4"
    callers:
      - name: GATK v4.2.15
        image: "broadinstitute/gatk:4.2.15"
        command: "gatk.sh ${PARAMS}"
        params:
          - "INPUT=${BAM}"
          - "OUTPUT=${OUTPUT}"
logger:
  logLevel: "off"