{{- if .Values.tls.publicIssuer.enabled -}}
apiVersion: cert-manager.io/v1
kind: {{ .Values.tls.publicIssuer.type }}
metadata:
  name: {{ .Values.tls.publicIssuer.name }}
  labels:
    {{- include "opencga.labels" . | nindent 4 }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ required "Cluster issues email is required!" .Values.tls.publicIssuer.acme.email }}
    privateKeySecretRef:
      name: "{{ .Values.tls.publicIssuer.name -}}-key"
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux
{{- end -}}