---
logLevel: "INFO"

# Number of seconds that session remains open without any activity [10 min]
cliSessionDuration: 600

## REST client configuration options
rest:
  host: "${OPENCGA.CLIENT.REST.HOST}"
  tokenAutoRefresh: true
  tlsAllowInvalidCertificates: false
  timeout: 90000
  query:
    batchSize: 200
    limit: 2000


## gRPC configuration options
grpc:
  host: "${OPENCGA.CLIENT.GRPC.HOST}"


## Configure the default behaviour when query variants
variant:
  unknownGenotype: "0/0"
