{{- if .Values.azureStorageAccount.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.azureStorageAccount.secretName }}
  labels:
    {{- include "opencga.labels" . | nindent 4 }}
type: "Opaque"
data:
  azurestorageaccountname: {{ .Values.azureStorageAccount.name | b64enc | quote }}
  azurestorageaccountkey: {{ .Values.azureStorageAccount.key | b64enc | quote }}
{{- end }}