name: OpenCGA Develop workflow

on:
  push:
    branches:
      - 'issue-1809'
#      - 'develop'
#      - 'release-*'
    paths:
      - '**.java'
      - '**pom.xml'
      - 'Dockerfile'
      - '**/workflows/main.yml'

jobs:
  build:
    name: OpenCGA Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ "1.8" ]
        mvnOptions:
          - "-Pstorage-mongodb"
          - "-Pstorage-hadoop -Phdp2.6"
          - "-Pstorage-hadoop -Phdp3.1"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '1'
      - name: "Set up JDK ${{ matrix.java }}"
        uses: actions/setup-java@v1
        with:
          java-version: "${{ matrix.java }}"
      - name: Maven Build (skip tests)
        run: "mvn -T 2 clean install -DskipTests -Dcheckstyle.skip ${{ matrix.mvnOptions }}"
      - name: Maven Validate
        run: "mvn validate ${{ matrix.mvnOptions }}"
  test:
    name: OpenCGA Test
    runs-on: ubuntu-20.04
    needs: build
    strategy:
      matrix:
        java: ["1.8"]
        mongodb:
        # - "4.0"
          - "4.2"
    services:
      mongodb:
        image: "mongo:${{ matrix.mongodb }}"
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '1'
      - name: "Set up JDK ${{ matrix.java }}"
        uses: actions/setup-java@v1
        with:
          java-version: "${{ matrix.java }}"
      - name: Build with Maven
        run: "mvn -T 2 clean install -Dcheckstyle.skip --fail-at-end -pl \'!:opencga-storage-mongodb,!:opencga-storage-hadoop,!:opencga-storage-hadoop-core\'"
      - name: Publish Test Report
        if: "${{ always() }}"
        uses: scacap/action-surefire-report@v1